story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='profile'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
import story1.urls as story1
import story5.urls as story5
import story6.urls as story6


urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', views.home, name="home"),
    path('stickers/', views.stickers, name="stickers"),
    path('profile/', include(story1, namespace='story1')),
    path('matkul/', include(story5, namespace='story5')),
    path('kegiatan/', include(story6, namespace='story6'))

]

urlpatterns += staticfiles_urlpatterns()

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:nama>', views.detail, name='detail'),
    path('addPeserta/<int:id>/<str:origin>', views.addPeserta, name='addPeserta'),
    path('delPeserta/<int:id>/<int:pk>/<str:origin>', views.delPeserta, name='delPeserta'),
    path('detailPeserta/<str:nama>', views.detailPeserta, name='detailPeserta'),
    path('addKegiatan/<int:id>/<str:origin>', views.addKegiatan, name='addKegiatan')
]

story6/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Peserta(models.Model):
    nama = models.CharField(max_length=20, unique=True)
    
    def __str__(self):
        return self.nama


    def get_absolute_url(self):
        urlnama = self.nama.replace(" ", "-")
        return reverse('story6:detailPeserta', args=[str(urlnama)])

class Kegiatan(models.Model):
    nama = models.CharField(max_length=20, unique=True)
    peserta = models.ManyToManyField(Peserta, blank=True)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        urlnama = self.nama.replace(" ", "-")
        return reverse('story6:detail', args=[str(urlnama)])

story6/forms.py
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Peserta, Kegiatan

class PesertaForm(ModelForm): 
    class Meta: 
        model = Peserta
        fields = '__all__'
        labels = {
            'nama': _('Add Peserta'),
        }
        widgets = {
            'nama': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Nama Peserta',
					}
				)
        }

class KegiatanForm(ModelForm): 
    class Meta: 
        model = Kegiatan
        fields = ('nama',)
        labels = {
            'nama': _(''),
        }        
        widgets = {
            'nama': forms.TextInput(
				attrs={
					'class': 'form-control',
                    'placeholder': 'Event name',
					}
				)
        }

story6/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .models import Kegiatan, Peserta
from .forms import PesertaForm, KegiatanForm

# Create your views here.
def index(request):  
    kegiatan = Kegiatan.objects.all()
    add_peserta = PesertaForm(request.POST or None)
    add_kegiatan = KegiatanForm(request.POST or None)
    if add_peserta.is_valid():
        add_peserta.save()
        add_peserta = PesertaForm()
    
    if add_kegiatan.is_valid():
        add_kegiatan.save()
        add_kegiatan = KegiatanForm()

    count = 3
    for i in kegiatan: 
        count += 1
    masonry_height = count // 3 * 500

    context = {
        'kegiatan': kegiatan,
        'add_peserta': add_peserta,
        'add_kegiatan': add_kegiatan,
        'height': masonry_height
    }
    return render(request, 'story6/index.html', context)

def detail(request, nama): 
    nama = nama.replace("-"," ")
    kegiatan = Kegiatan.objects.get(nama=nama)
    add_peserta = PesertaForm(request.POST or None)
    if add_peserta.is_valid():
        add_peserta.save()
        add_peserta = PesertaForm()

    context = {
        'kegiatan': kegiatan,
        'add_peserta': add_peserta
    }
    return render(request, 'story6/detail.html', context)

def addKegiatan(request, id, origin):
    if request.method == 'POST':
        if origin == 'index':
            kegiatan = request.POST['nama']

            new, status = Kegiatan.objects.get_or_create(nama=kegiatan)
            if status: 
                # kegiatan belum pernah ada
                new.save()
                messages.add_message(request, messages.SUCCESS, "{} is successfully created.".format(new))
            else: 
                # kegiatan sudah ada
                messages.add_message(request, messages.WARNING, "{} already exists.".format(new))
                
            return redirect(reverse('story6:detail', args=[new.nama]))
        
        elif origin == 'detailPeserta':
            peserta = Peserta.objects.get(id=id)
            kegiatan = request.POST['nama']

            new, status = Kegiatan.objects.get_or_create(nama=kegiatan)
            if status: 
                # add peserta baru ke kegiatan
                new.save()
                peserta.kegiatan_set.add(new)
                messages.add_message(request, messages.SUCCESS, "{} is now participating in {}".format(peserta, new))
            else: 
                try: 
                    # peserta lama udah ada di kegiatan
                    peserta.kegiatan_set.get(nama=new)
                    messages.add_message(request, messages.WARNING, "{} was already participating in {}".format(peserta, new))
                except: 
                    # peserta lama belom ada di kegiatan
                    peserta.kegiatan_set.add(new)
                    messages.add_message(request, messages.SUCCESS, "{} is now participating in {}".format(peserta, new))
            
            return redirect(reverse('story6:detailPeserta', args=[peserta.nama]))

def detailPeserta(request, nama): 
    nama = nama.replace("-"," ")
    peserta = Peserta.objects.get(nama=nama)
    add_kegiatan = KegiatanForm(request.POST or None)
    if add_kegiatan.is_valid():
        add_kegiatan.save()
        add_kegiatan = KegiatanForm()

    context = {
        'peserta': peserta,
        'add_kegiatan': add_kegiatan
    }
    return render(request, 'story6/detailPeserta.html', context)

def addPeserta(request, id, origin): 
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id=id)
        peserta = request.POST['nama']

        new, status = Peserta.objects.get_or_create(nama=peserta)
        if status: 
            # add peserta baru ke kegiatan
            new.save()
            kegiatan.peserta.add(new)
            messages.add_message(request, messages.SUCCESS, "{} was successfully added to {}".format(new, kegiatan.nama))
        else: 
            try: 
                # peserta lama udah ada di kegiatan
                kegiatan.peserta.get(nama=new)
                messages.add_message(request, messages.WARNING, "{} was already participating in {}".format(new, kegiatan.nama))
            except: 
                # peserta lama belom ada di kegiatan
                kegiatan.peserta.add(new)
                messages.add_message(request, messages.SUCCESS, "{} was successfully added to {}".format(new, kegiatan.nama))
    
    if origin == 'index': 
        return redirect(reverse('story6:index'))
    elif origin == 'detail': 
        return redirect(reverse('story6:detail', args=[kegiatan.nama]))

def delPeserta(request, id, pk, origin): 
    kegiatan = Kegiatan.objects.get(id=id)

    try: 
        delPeserta = get_object_or_404(Peserta, pk=pk)
        kegiatan.peserta.remove(delPeserta)
        messages.add_message(request, messages.SUCCESS, "{} successfully removed".format(delPeserta))
    except: 
        messages.add_message(request, messages.SUCCESS, "{} didn't exist".format(delPeserta))
           
    if origin == 'index': 
        return redirect(reverse('story6:index'))
    elif origin == 'detail': 
        return redirect(reverse('story6:detail', args=[kegiatan.nama]))
    

story6/templates/story6/detail.html
{% extends 'base.html' %}

{% block title %} Detail {{kegiatan}} | Nur Wasi Na'wa {% endblock %}

{% block body %}
<div class="container my-3">
    <div class="row">
        <div class="col-md-8">
            <h3>{{kegiatan.nama}}</h3>
            <h4 class="card-header">Participants:</h4>
            <ul class="mt-3">
                {% for peserta in kegiatan.peserta.all %}
                <li class="mb-2">{{ peserta }}
                    <div class="float-right">
                        <a href="{% url 'story6:delPeserta' id=kegiatan.id pk=peserta.id origin='detail' %}" class="btn btn-danger" style="border-radius: 50%; font-size: 1rem;"><i class="fa fa-trash"></i></a>
                    </div>  
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4">
            <div class="card mb-2">
                
                <form action="{% url 'story6:addPeserta' id=kegiatan.id origin='detail' %}" method="POST" class="m-3">
                    {% csrf_token %}
                    {{ add_peserta }}
                </form>
            </div>
            <a href="{% url 'story6:index' %}" class="btn btn-primary btn-lg w-25 float-right">Back</a>
        </div>
    </div>
</div>

{% endblock %}

story6/templates/story6/detailPeserta.html
{% extends 'base.html' %}

{% block title %} Detail {{peserta}} | Nur Wasi Na'wa {% endblock %}

{% block body %}
<div class="container my-3">
    <div class="row">
        <div class="col-md-8">
            <h3>{{peserta.nama}}</h3>
            <h4 class="card-header">Berpartisipasi pada event:</h4>
            <ul class="mt-3">
                {% for kegiatan in peserta.kegiatan_set.all %}
                <li>{{ kegiatan }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4">
            <div class="card mb-2">
                <div class="card-header">
                    <h4>Tambahkan event lain!</h4>
                </div>
                
                <form action="{% url 'story6:addKegiatan' id=peserta.id origin='detailPeserta' %}" method="POST" class="m-3">
                    {% csrf_token %}
                    {{ add_kegiatan }}
                </form>
            </div>
            <a href="{% url 'story6:index' %}" class="btn btn-primary btn-lg w-25 float-right">Back</a>
        </div>
    </div>
</div>

{% endblock %}

story6/templates/story6/index.html
{% extends 'base.html' %}

{% block title %} Daftar Kegiatan | Nur Wasi Na'wa {% endblock %}

{% block head %}
<style>
.masonry { 
    display: flex;
    flex-flow: column wrap;
    width: 100%;
    max-height: {{height}}px;    
  }
  
  .masonry-brick {
    margin: 0 1rem 1rem 0; /* Some gutter */
    padding: 0;
  }
</style>
{% endblock %}

{% block body %}
<div class="container my-4">
    <div class="masonry">
    {% for keg in kegiatan %}
        <div class="card masonry-brick col-md-4 ">
            <div class="card-header text-center">
                <h3> <a href="{{keg.get_absolute_url}}">{{ keg.nama }}</a></h3> 
            </div>
            <div class="card-body">
                <h3>Peserta:</h3>
                    <ul>
                        {% for peserta in keg.peserta.all %}
                            <li class="mb-2">
                                <a href="{{peserta.get_absolute_url}}">{{ peserta.nama }}</a>
                                <div class="float-right">
                                    <a href="{% url 'story6:delPeserta' id=keg.id pk=peserta.id origin='index' %}" class="btn btn-danger" style="border-radius: 50%; font-size: 1rem;"><i class="fa fa-trash"></i></a>
                                </div>  
                            </li>                                                     
                        {% endfor%}
                    </ul>
            </div>
            <div class="card-footer p-4">
                <form action="{% url 'story6:addPeserta' id=keg.id origin='index' %}" method="POST">
                    {% csrf_token %}
                    {{ add_peserta }}
                </form>
            </div>
            
        </div> 
    {% endfor %}
        <div class="card masonry-brick col-md-4">
            <div class="card-header">
                <h3>Add new event</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'story6:addKegiatan' id='0' origin='index' %}" method="POST">
                    {% csrf_token %}
                    {{ add_kegiatan }}
                    <input type="submit" class="btn btn-lg btn-primary mt-3 float-right">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}