story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='profile'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
import story1.urls as story1
import story5.urls as story5
import story6.urls as story6


urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', views.home, name="home"),
    path('stickers/', views.stickers, name="stickers"),
    path('profile/', include(story1, namespace='story1')),
    path('matkul/', include(story5, namespace='story5')),
    path('kegiatan/', include(story6, namespace='story6'))

]

urlpatterns += staticfiles_urlpatterns()

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.matkul, name='matkul'),
    path('details/<int:id>', views.details, name='details'),
    path('add/', views.addMatkul, name='add'),
    path('delete/<int:id>', views.delMatkul, name='del')
]

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:nama>', views.detail, name='detail'),
    path('addPeserta/<int:id>/<str:origin>', views.addPeserta, name='addPeserta'),
    path('delPeserta/<int:id>/<int:pk>/<str:origin>', views.delPeserta, name='delPeserta'),
    path('detailPeserta/<str:nama>', views.detailPeserta, name='detailPeserta'),
    path('addKegiatan/<int:id>/<str:origin>', views.addKegiatan, name='addKegiatan')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- <link href="https://necolas.github.io/normalize.css/8.0.1/normalize.css" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css?family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chango|Diplomata&display=swap" rel="stylesheet"> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- Load font awesome icons -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.12.0/css/all.css">
    <!-- Latest compiled and minified CSS -->
    
    {% if not home %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">        
    {% endif %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    {% block home %} {% endblock %}
    <link rel="stylesheet" href="{% static "story4/style.css" %}">
    {% block head %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
<!-- navbar -->
<nav class="nav">
    <div class="container-fluid">
        <div id="mainListDiv" class="main_list">
            <ul class="navlinks">
                <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                {% if home %}
                    <li class="nav-item"><a class="nav-link" href="#profile">Profile</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'stickers' %}">Recommendations</a></li>
                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Daftar Story
                    </a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'story1:profile' %}">Halaman Profil</a>
                        <a class="dropdown-item" href="{% url 'story5:matkul' %}">Mata Kuliah</a>
                        <a class="dropdown-item" href="{% url 'story6:index' %}">Kegiatan Organizer</a>
                    </div>
                </li>
            </ul>
        </div>
        <span class="navTrigger">
            <i></i>
            <i></i>
            <i></i>
        </span>
    </div>
</nav>
<!------------------ landing ------------------>
{% if home %}
    <div class="landing container-fluid">
        <div class="name">              
            <h1>--nwn</h1>
        </div>
    </div>
{% else %}
    <div class="landing-all container-fluid">
        <div class="name">   
            <h1>--nwn</h1>
        </div>
    </div>
{% endif %}

{% if messages %}
<ul class="messages container mt-4 mb-0">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %}>{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% block body %} {% endblock %}
    
<!------------------ footer ------------------>
<div class="footer container-fluid"> </div>


<!-- The social media icon bar -->
<div id="icons" class="icon-bar h3">
    <a href="https://www.instagram.com/nurwasinawa/" class="instagram"><i class="fab fa-instagram"></i></a>
    <a href="https://gitlab.com/nwasinawa" class="gitlab"><i class="fab fa-gitlab"></i></a>
  </div>
</body>
<!-- Jquery needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Function used to shrink nav bar removing paddings and adding black background -->
<script>
    $(window).scroll(function() {
        if ($(document).scrollTop() > 50) {
            $('.nav').addClass('affix');
            console.log("OK");
        } else {
            $('.nav').removeClass('affix');
        }
    });

    $('.navTrigger').click(function () {
    $(this).toggleClass('active');
    console.log("Clicked menu");
    $("#mainListDiv").toggleClass("show_list");
    $("#mainListDiv").fadeIn();

});

</script>
</html>

templates/stickers.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Recommendation | Nur Wasi Na'wa {% endblock %}

{% block body %}

<div id="stickers" class="container">
    <div class="row text-center">
        <hr>
        <h2>Recommendation</h2>
        <hr>
    </div>
<div class="row">
    <div class="project col-sm-4 col-md-3">
        <div class="card">
            <img class="card-img-top" src="{% static "story4/images/The-Gifted.jpg" %}">
            <div class="snippet card-body">
                <h4 class="card-title">The Gifted</h4>
                <p class="card-text">Ritdha High School, a school with a "Gifted Program" that holds a special class for a handful of "special" students that were chosen by the school administrator.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
    <div class="project col-sm-4  col-md-3">
        <div class="card">
            <div class="preview">
                <img class="card-img-top" src="{% static "story4/images/tgg.jpg" %}">
            </div>
            <div class="snippet card-body">
                <h4 class="card-title">The Gifted Graduation</h4>
                <p class="card-text">Two years have passed and the new school year begins again. With it comes the resurrection of the Gifted program,  and a hidden threat from the Ministry led by Darin, a new teacher.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
    <div class="project col-sm-4  col-md-3">
        <div class="card">
            <div class="preview">
                <img class="card-img-top" src="{% static "story4/images/gfn.jpg" %}">
            </div>
            <div class="snippet card-body">
                <h4 class="card-title">Girl From Nowhere</h4>
                <p class="card-text">A mysterious, clever girl named Nanno transfers to different schools, exposing the lies and misdeeds of the students and faculty at every turn.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
    <div class="project col-sm-4 col-md-3">
        <div class="card">
            <div class="preview">
                <img class="card-img-top" src="{% static "story4/images/socialsyndrome.jpg" %}">
            </div>
            <div class="snippet card-body">
                <h4 class="card-title">Social Syndrome</h4>
                <p class="card-text">When the digital age is more dangerous than you think.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
</div>

<div class="row mx-auto">
    <div class="project col-sm-4  col-md-3">
        <div class="card">
            <div class="preview">
                <img class="card-img-top" src="{% static "story4/images/bad-genius.jpeg" %}">
            </div>
            <div class="snippet card-body">
                <h4 class="card-title">Bad Genius</h4>
                <p class="card-text">Lynn, a genius high school student who makes money by cheating tests, receives a new task that leads her to set foot on Sydney, Australia.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
    <div class="project col-sm-4 col-md-3">
        <div class="card">
            <div class="preview">
                <img class="card-img-top" src="{% static "story4/images/Homestay.jpg" %}">
            </div>
            <div class="snippet card-body">
                <h4 class="card-title">Homestay</h4>
                <p class="card-text">"You were granted a prize." A mysterious man who calls himself the Guardian told me as we were standing on the outer wall of the hospital building that was turned sideways as if we were defying gravity.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
    <div class="project col-sm-4 col-md-3">
        <div class="card">
            <img class="card-img-top" src="{% static "story4/images/classicagain.jpg" %}">
            <div class="snippet card-body">
                <h4 class="card-title">Classic Again</h4>
                <p class="card-text">In a love triangle that miraculously mirrors her mother's romance years ago, a young woman lets her heart lead.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
    <div class="project col-sm-4  col-md-3">
        <div class="card">
            <div class="preview">
                <img class="card-img-top" src="{% static "story4/images/A-gift.jpg" %}">
            </div>
            <div class="snippet card-body">
                <h4 class="card-title">A Gift</h4>
                <p class="card-text">The story of 6 people who are trying to overcome challenges that life has thrown at them.</p>
                <a href="#" class="btn btn-outline-secondary">read more.</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}